
stages:
  - build
  - deploy

.change_file_permissions: &change_file_permissions |
  find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;    
  find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;
  

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_DIGITAL_OCEAN_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  ssh-keyscan latinaeduca.com >> ~/.ssh/known_hosts
  chmod 644 ~/.ssh/known_hosts


.init_ssh_qa: &init_ssh_qa |
  eval $(ssh-agent -s)
  echo "$SSH_DIGITAL_OCEAN_PRIVATE_KEY_QA" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  ssh-keyscan latinaeduca.com >> ~/.ssh/known_hosts
  chmod 644 ~/.ssh/known_hosts

building-prod:
  stage: build
  before_script:
    - echo "API script"
    - *init_ssh
    - *change_file_permissions
  script:
    - ssh -o StrictHostKeyChecking=no $USER_DIGITAL_OCEAN@$IPADDRESS_DIGITAL_OCEAN "cd /var/www/html/builds/api; git remote set-url origin https://andresdanilo0507:YOUR_GITLAB_ACCESS_TOKEN@gitlab.com/rojodi-sistema-academico/backend.git;git pull origin main; composer install; php artisan optimize;bash restart_queue.sh"
  only:
    - main

building-qa:
  stage: build
  before_script:
    - echo "API script"
    - *init_ssh_qa
    - *change_file_permissions
  script:
    - ssh -o StrictHostKeyChecking=no $USER_DIGITAL_OCEAN_QA@$IPADDRESS_DIGITAL_OCEAN_QA "cd /var/www/html/builds/api; git remote set-url origin https://andresdanilo0507:YOUR_GITLAB_ACCESS_TOKEN@gitlab.com/rojodi-sistema-academico/backend.git;git pull origin qa; composer install; php artisan optimize;bash restart_queue.sh"
  only:
    - qa


deploying:
  stage: deploy
  script:
    - echo "Deployed"
  only:
    - main
    - qa