export default [
  { heading: "Procesos Académicos", subject: "Procesos Académicos" },
  {
    title: "Periodos académicos",
    icon: { icon: "tabler-school-bell" },
    to: "academic-processes-periods",
    subject: "AcademicPeriods",
  },
  {
    title: "Lista de mérito",
    icon: { icon: "tabler-award" },
    to: "academic-processes-list-of-merit",
    subject: "ListOfMerit",
  },
  {
    title: "Matrículas Registra",
    icon: { icon: "tabler-id" },
    to: "academic-processes-enrollment",
    subject: "Enrollment",
  },
  {
    title: "Historial académico",
    icon: { icon: "tabler-clipboard-list" },
    to: "academic-processes-academic-history",
    subject: "AcademicHistory",
  },
  {
    title: "Familia Productiva",
    icon: { icon: "tabler-hexagons" },
    to: "productive-family-list",
    subject: "ProductiveFamily",
  },
  {
    title: "Programa de Estudio",
    icon: { icon: "tabler-book-2" },
    to: "study-program-list",
    subject: "StudyProgram",
  },
  {
    title: "Tipos de planes de Estudio",
    icon: { icon: "tabler-backpack" },
    to: "study-plan-types-list",
    subject: "StudyPlanType",
  },
  {
    title: "Plan de Estudio",
    icon: { icon: "tabler-book" },
    to: "study-plan-list",
    subject: "StudyPlan",
  },
  {
    title: "Ciclos",
    icon: { icon: "tabler-calendar-event" },
    to: "cycles-list",
    subject: "Cycle",
  },
  {
    title: "Tipos de módulos",
    icon: { icon: "tabler-blocks" },
    to: "modules-types-list",
    subject: "ModuleType",
  },
  {
    title: "Módulos",
    icon: { icon: "tabler-border-all" },
    to: "modules-list",
    subject: "Module",
  },
  {
    title: "Tipos de cursos",
    icon: { icon: "tabler-vocabulary" },
    to: "courses-types-list",
    subject: "CourseType",
  },
  {
    title: "Cursos",
    icon: { icon: "tabler-books" },
    to: "courses-list",
    subject: "Course",
  },
  {
    title: "Periodos",
    icon: { icon: "tabler-table" },
    to: "period-list",
    subject: "Period",
  },
  {
    title: "Turnos",
    icon: { icon: "tabler-hourglass-high" },
    to: "shifts-list",
    subject: "Shift",
  },
  {
    title: "Secciones",
    icon: { icon: "tabler-layout-grid" },
    to: "sections-list",
    subject: "Section",
  },
  {
    title: "Clases",
    icon: { icon: "tabler-chalkboard" },
    to: "classroom-list",
    subject: "Classroom",
  },
];
